// <auto-generated />
using System;
using Interview_Test.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interview_Test.Infrastructure.Migrations
{
    [DbContext(typeof(InterviewTestDbContext))]
    partial class InterviewTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interview_Test.Models.PermissionModel", b =>
                {
                    b.Property<long>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionId"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("PermissionTb", (string)null);
                });

            modelBuilder.Entity("Interview_Test.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("RoleTb", (string)null);
                });

            modelBuilder.Entity("Interview_Test.Models.RolePermissionMappingModel", b =>
                {
                    b.Property<Guid>("RolePermissionMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionMappingId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionMappingTb", (string)null);
                });

            modelBuilder.Entity("Interview_Test.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserTb", (string)null);
                });

            modelBuilder.Entity("Interview_Test.Models.UserProfileModel", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProfileId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("UserProfileTb", (string)null);
                });

            modelBuilder.Entity("Interview_Test.Models.UserRoleMappingModel", b =>
                {
                    b.Property<Guid>("UserRoleMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleMappingId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleMappingTb", (string)null);
                });

            modelBuilder.Entity("Interview_Test.Models.RolePermissionMappingModel", b =>
                {
                    b.HasOne("Interview_Test.Models.PermissionModel", "Permission")
                        .WithMany("RolePermissionMappings")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interview_Test.Models.RoleModel", "Role")
                        .WithMany("RolePermissionMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Interview_Test.Models.UserProfileModel", b =>
                {
                    b.HasOne("Interview_Test.Models.UserModel", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Interview_Test.Models.UserProfileModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Test.Models.UserRoleMappingModel", b =>
                {
                    b.HasOne("Interview_Test.Models.RoleModel", "Role")
                        .WithMany("UserRoleMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interview_Test.Models.UserModel", "User")
                        .WithMany("UserRoleMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Test.Models.PermissionModel", b =>
                {
                    b.Navigation("RolePermissionMappings");
                });

            modelBuilder.Entity("Interview_Test.Models.RoleModel", b =>
                {
                    b.Navigation("RolePermissionMappings");

                    b.Navigation("UserRoleMappings");
                });

            modelBuilder.Entity("Interview_Test.Models.UserModel", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoleMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
